//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_platter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_platter()
        {
            this.Rating_tbl = new HashSet<Rating_tbl>();
        }
    
        public int platter_id { get; set; }
        public string platter_name { get; set; }
        public string platter_description { get; set; }
        public byte[] platter_image { get; set; }
        public Nullable<decimal> platter_price { get; set; }
        public Nullable<int> Rest_id { get; set; }
        public Nullable<int> secret_code { get; set; }
        public int rating_total { get; set; }
        public int rating_count { get; set; }
        public Nullable<decimal> rating { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating_tbl> Rating_tbl { get; set; }
        public virtual tbl_restaurent tbl_restaurent { get; set; }
    }
}
