//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foodies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_restaurent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_restaurent()
        {
            this.tbl_platter = new HashSet<tbl_platter>();
        }
    
        public int Rest_id { get; set; }
        public string Rest_name { get; set; }
        public string Rest_location { get; set; }
        public string Rest_phone { get; set; }
        public Nullable<int> secret_code { get; set; }
        public Nullable<int> User_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_platter> tbl_platter { get; set; }
        public virtual User_tbl User_tbl { get; set; }
    }
}
